# Upon a push to master, this workflow will:
# -- run all tests (unit tests and doctests)

name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-ubuntu:
    name: "Test python ${{matrix.python-version}} on Ubuntu Focal Fossa"
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install PyUVS and testing utilities
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[test]
      - name: Test with pytest
        run: |
          python -m pytest ./pyuvs

  test-macos:
    name: "Test python ${{matrix.python-version}} on macOS Big Sur 11"
    runs-on: macos-11

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install PyUVS and testing utilities
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[test]
      - name: Test with pytest
        run: |
          python -m pytest ./pyuvs